# Generated by Django 4.1.2 on 2022-10-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='sub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
